#!/sbin/sh
#
# Liverpool John Moores University
#
#ident	"$Id: gcnforwarder,v 1.3 2005-02-03 10:46:36 cjm Exp $"
GCN_FORWARDER_HOME=/space/home/dev/bin/estar/classes
GCN_FORWARDER_PIDFILE=/space/home/dev/bin/estar/classes/gcnforwarder.pid
GCN_FORWARDER_OUPTUT_FILE=/space/home/dev/tmp/estar/gcn_forwarder_output.txt
# Some .sh equivalent stuff of environment in
# lt_environment.csh
CLASSPATH="."
list=`ls /space/home/dev/bin/estar/javalib/*.jar`
for i in $list; do
    CLASSPATH=${CLASSPATH}":"$i
done

LD_LIBRARY_PATH=/space/home/dev/bin/lib/${HOSTTYPE}
export CLASSPATH 
export LD_LIBRARY_PATH

case "$1" in
start)
	/bin/rm -f ${GCN_FORWARDER_PIDFILE}
	cd ${GCN_FORWARDER_HOME}
	echo "GCN Forwarder start."
	# 150.204.240.107 - ltobs9
	# 161.72.57.3 - ltdmz1/ltproxy - LT external IP
	# 132.160.98.239 - ftnproxy
	# 150.203.153.202 - ftsproxy
	# 144.173.229.16 dastardly.astro.ex.ac.uk
	# 144.173.229.20 estar.astro.ex.ac.uk
	java org.estar.gcn.GCNDatagramForwarder -forward_port 5169 -forward_address 150.204.240.107 -forward_port 5169 -forward_address 161.72.57.3 -forward_port 5169 -forward_address 132.160.98.239 -forward_port 5169 -forward_address 150.203.153.202-forward_address 144.173.229.16 -forward_port 5184 -forward_address 144.173.229.20 -forward_port 5184 1> ${GCN_FORWARDER_OUPTUT_FILE} 2>&1 &
	echo $! > ${GCN_FORWARDER_PIDFILE}
	;;
stop)
	echo "GCN Forwarder  stop."
	PID=`cat ${GCN_FORWARDER_PIDFILE}`
	kill ${PID}
	;;
*)
	echo "Usage: $0 {start|stop}"
	exit 1
	;;
esac

if [ $? != 0 ]; then
	echo "$status"
	exit 1
fi
exit 0

